/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RobotsMapRouteImport } from './routes/robots-map'
import { Route as IndexRouteImport } from './routes/index'

const RobotsMapRoute = RobotsMapRouteImport.update({
  id: '/robots-map',
  path: '/robots-map',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/robots-map': typeof RobotsMapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/robots-map': typeof RobotsMapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/robots-map': typeof RobotsMapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/robots-map'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/robots-map'
  id: '__root__' | '/' | '/robots-map'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RobotsMapRoute: typeof RobotsMapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/robots-map': {
      id: '/robots-map'
      path: '/robots-map'
      fullPath: '/robots-map'
      preLoaderRoute: typeof RobotsMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RobotsMapRoute: RobotsMapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
